/** Locale chrome for the Capability Inspector. Server DTOs stay text-free. */
export type BuiltinTogglesLocaleKey =
  | 'tab' | 'loading' | 'error' | 'retry' | 'inspectorIntro' | 'searchPlaceholder' | 'searchEmpty' | 'searchEmptyAnomalies' | 'searchEmptyAnomaliesFiltered' | 'resultCount' | 'presentationLocale'
  | 'compatibilityHeading' | 'compatibilityStatusDrifted' | 'compatibilityStatusNoDrift' | 'compatibilityExplainDrifted' | 'compatibilityExplainIdentityMismatch' | 'compatibilityExplainEvidenceIncomplete' | 'compatibilityExplainIdentityUnavailable' | 'compatibilityExplainUnverified' | 'compatibilityExplainVerified' | 'compatibilityExplainNoDrift' | 'runtimeIdentityLabel' | 'noFindings' | 'copyDiagnostics' | 'diagnosticsCopied' | 'diagnosticsCopyFailed'
  | 'filterAll' | 'filterCategory' | 'filterManagementPlane' | 'filterCompositionScope' | 'filterPolicy' | 'filterVerification' | 'filterRuntime' | 'filterAnomalies'
  | 'capabilityName' | 'presetManaged' | 'effectiveDisabled' | 'effectiveEnabled' | 'detailsShow' | 'detailsHide' | 'lockReason' | 'compositionScope'
  | 'mutationControls' | 'forceEnable' | 'forceDisable' | 'restoreInheritance' | 'controlsUnavailable' | 'remoteReadOnly' | 'remoteReadOnlyEligible' | 'mutationFailed' | 'mutationSubmitted' | 'restoreSubmitted'
  | 'copyCopied' | 'copyFailed'
  | 'expectedPackage' | 'reviewed' | 'reviewedReference' | 'declaredInject' | 'dependencyEvidence' | 'leafReview' | 'compatibilityFindings' | 'eligibilityReasons' | 'limitations' | 'provides' | 'consumers'
  | 'profilePersistence'
  | 'yes' | 'no' | 'none' | 'unknown' | 'noEvidence' | 'injectNotDeclared' | 'injectDeclaredEmpty' | 'dependencyObserved'
  | 'verificationVerified' | 'verificationDrifted' | 'verificationUnverified' | 'verificationNoDrift' | 'verificationEvidenceIncomplete' | 'verificationIdentityMismatch' | 'verificationUnreviewed' | 'verificationNotApplicable'
  | 'runtimeIdentityMatched' | 'runtimeIdentityMismatched' | 'runtimeIdentityUnavailable'
  | 'profileInherited' | 'profileExplicitlyEnabled' | 'profileExplicitlyDisabled' | 'profileUnavailable' | 'profileNotApplicable' | 'profileWritable' | 'profileUnwritable'
  | 'lifecycleInactive' | 'lifecyclePending' | 'lifecycleLoading' | 'lifecycleActive' | 'lifecycleFailed' | 'lifecycleUnloading' | 'lifecycleUnknown'
  | 'findingMissingExpectedEntry' | 'findingNewOfficialEntry' | 'findingPackageIdentityChanged' | 'findingDeclaredInjectChanged' | 'findingBaselinePackageUnknown' | 'findingDuplicateRuntimeId' | 'findingRuntimeReleaseIdentityUnavailable' | 'findingRuntimeReleaseIdentityMismatch' | 'findingRuntimeAugmentationShapeChanged' | 'findingRuntimeAugmentationIdConflictsBaseline'
  | 'eligibilityNotManageable' | 'eligibilityMissingRuntimeEntry' | 'eligibilityReviewedBaselineMissing' | 'eligibilityReviewedSafeLeafEvidenceMissing' | 'eligibilityTargetStructuralDrift' | 'eligibilityGlobalStructuralDrift' | 'eligibilityRuntimeIdentityMismatch' | 'eligibilityProfileNotPersistable' | 'eligibilityAgentPresetScope'
  | 'limitationRuntimeIdentityUnavailable' | 'limitationConsumerGraphNotExposed'
  | 'leafReviewReviewedSafeUiLeaf' | 'leafReviewLockedDependency' | 'leafReviewNotReviewed'
  | 'categoryPresentation' | 'categoryAgent' | 'categoryTransport' | 'categoryInfrastructure' | 'categoryUnknown'
  | 'planeBrowser' | 'planeHost' | 'planeAgentPreset' | 'planeUnknown' | 'policyManageable' | 'policyLocked' | 'lockSelf' | 'lockCore' | 'lockUnlisted' | 'lockExternal' | 'lockAgentPreset'

export const zh: Record<BuiltinTogglesLocaleKey, string> = {
  tab: '内置插件', loading: '正在读取能力检查结果…', error: '能力检查暂时不可用。', retry: '重试', presentationLocale: 'zh',
  inspectorIntro: '检查当前 Host Loader 中的所有能力。组成检查是检查结论，写入资格是服务端对单项写入的独立授权；不可操作的条目仍保留在此处供检查。',
  searchPlaceholder: '搜索 ID、包名、类别或管理平面', searchEmpty: '没有匹配的能力。', searchEmptyAnomalies: '当前未发现异常项。', searchEmptyAnomaliesFiltered: '当前筛选条件下未发现异常项。', resultCount: '显示 {count} / {total} 个能力',
  compatibilityHeading: '组成检查 / 兼容性检查', compatibilityStatusDrifted: '发现结构漂移', compatibilityStatusNoDrift: '未发现结构漂移', compatibilityExplainDrifted: '已发现可复核的结构差异；检查仍可用，但这些发现需要随兼容性报告一并评估。', compatibilityExplainIdentityMismatch: '宿主公开的运行时发布身份与已审阅基线不匹配；这不是对宿主健康状况的泛化判断。', compatibilityExplainEvidenceIncomplete: '已审阅基线中有未能独立确认的证据，因此结果保持未验证。', compatibilityExplainIdentityUnavailable: '宿主未公开可绑定的运行时发布身份；这不表示系统损坏或能力不可用。', compatibilityExplainUnverified: '当前可用证据不足以作出已验证结论；请查看下面的具体发现。', compatibilityExplainVerified: '结构与运行时身份均已核对，未发现结构漂移。', compatibilityExplainNoDrift: '未发现结构漂移；仅缺少上游未提供的运行时发布身份，已保留在机器证据中。', runtimeIdentityLabel: '运行时身份', noFindings: '没有可报告的发现。', copyDiagnostics: '复制诊断信息', diagnosticsCopied: '已复制脱敏诊断信息。', diagnosticsCopyFailed: '无法复制诊断信息。',
  filterAll: '全部', filterCategory: '类别', filterManagementPlane: '管理平面', filterCompositionScope: '组合范围', filterPolicy: '策略', filterVerification: '检查状态', filterRuntime: '运行状态', filterAnomalies: '仅异常项',
  capabilityName: '名称：{name}', presetManaged: '由 Agent 预设管理', effectiveDisabled: '当前有效：停用', effectiveEnabled: '当前有效：启用', detailsShow: '查看机器证据', detailsHide: '收起机器证据', lockReason: '锁定原因', compositionScope: '组合范围',
  mutationControls: '写入控制', forceEnable: '强制启用', forceDisable: '强制禁用', restoreInheritance: '恢复继承', controlsUnavailable: '此条目没有可执行控制', remoteReadOnly: '当前为远程只读模式；配置写入仅允许本机回环且同源请求。', remoteReadOnlyEligible: '本项本可修改，但当前为远程只读模式，无法执行写入。', mutationFailed: '操作失败：{message}', mutationSubmitted: '已提交。已重新读取服务端状态；刷新页面后客户端效果才会更新。', restoreSubmitted: '已恢复配置档继承。已重新读取服务端状态；DSH 配置档/HMR 重组期间有效状态可能暂时不同。',
  copyCopied: '已复制', copyFailed: '复制失败',
  expectedPackage: '预期包', reviewed: '是否已审阅', reviewedReference: '审阅引用 / 溯源', declaredInject: '注入声明证据', dependencyEvidence: '依赖证据', leafReview: '叶子审阅结论', compatibilityFindings: '组成检查发现', eligibilityReasons: '写入资格原因', limitations: '限制', provides: '提供', consumers: '消费者', profilePersistence: '配置档持久化预检',
  yes: '是', no: '否', none: '无', unknown: '未确认', noEvidence: '无可用证据', injectNotDeclared: '已审阅补丁未声明注入声明', injectDeclaredEmpty: '已声明为空注入集合', dependencyObserved: '已观察',
  verificationVerified: '已验证', verificationDrifted: '已漂移', verificationUnverified: '未验证', verificationNoDrift: '结构未见漂移', verificationEvidenceIncomplete: '证据不完整', verificationIdentityMismatch: '运行时身份不匹配', verificationUnreviewed: '未审阅', verificationNotApplicable: 'Agent 预设，不参与基线验证', runtimeIdentityMatched: '匹配', runtimeIdentityMismatched: '不匹配', runtimeIdentityUnavailable: '不可用',
  profileInherited: '继承默认值', profileExplicitlyEnabled: '已强制启用', profileExplicitlyDisabled: '已强制禁用', profileUnavailable: '不可用', profileNotApplicable: '不适用（Agent 预设组合）', profileWritable: '可写', profileUnwritable: '不可写',
  lifecycleInactive: '未挂载', lifecyclePending: '等待依赖', lifecycleLoading: '加载中', lifecycleActive: '运行中', lifecycleFailed: '挂载失败', lifecycleUnloading: '卸载中', lifecycleUnknown: '未确认',
  findingMissingExpectedEntry: '缺少预期条目', findingNewOfficialEntry: '新增官方条目', findingPackageIdentityChanged: '包身份漂移', findingDeclaredInjectChanged: '注入声明漂移', findingBaselinePackageUnknown: '基线包身份未确认', findingDuplicateRuntimeId: '重复 Loader id', findingRuntimeReleaseIdentityUnavailable: '运行时身份不可用', findingRuntimeReleaseIdentityMismatch: '运行时身份不匹配', findingRuntimeAugmentationShapeChanged: '运行时增强形态变化', findingRuntimeAugmentationIdConflictsBaseline: '运行时增强 id 与基线冲突',
  eligibilityNotManageable: '不在可管理允许列表中', eligibilityMissingRuntimeEntry: '缺少运行时条目', eligibilityReviewedBaselineMissing: '缺少已审阅基线', eligibilityReviewedSafeLeafEvidenceMissing: '缺少安全叶子证据', eligibilityTargetStructuralDrift: '目标结构漂移', eligibilityGlobalStructuralDrift: '全局结构漂移', eligibilityRuntimeIdentityMismatch: '运行时身份不匹配', eligibilityProfileNotPersistable: '配置档无法安全写入', eligibilityAgentPresetScope: 'Agent 预设组合条目不是宿主写入目标',
  limitationRuntimeIdentityUnavailable: '运行时发布身份不可用', limitationConsumerGraphNotExposed: '未公开完整消费者关系图',
  leafReviewReviewedSafeUiLeaf: '已审阅的安全界面叶子', leafReviewLockedDependency: '锁定依赖', leafReviewNotReviewed: '未审阅',
  categoryPresentation: '界面功能', categoryAgent: '模型与智能体', categoryTransport: '传输', categoryInfrastructure: '系统基础', categoryUnknown: '未确认类别', planeBrowser: '浏览器', planeHost: '宿主', planeAgentPreset: 'Agent 预设', planeUnknown: '未确认平面', policyManageable: '可管理', policyLocked: '已锁定', lockSelf: '插件自身', lockCore: '核心基础设施', lockUnlisted: '未在允许列表中', lockExternal: '外部插件', lockAgentPreset: 'Agent 预设组合条目',
}

export const en: Record<BuiltinTogglesLocaleKey, string> = {
  tab: 'Built-ins', loading: 'Reading capability inspection…', error: 'Capability inspection is temporarily unavailable.', retry: 'Retry', presentationLocale: 'en',
  inspectorIntro: 'Inspect every Loader capability in the current Host. Compatibility is an inspection conclusion; mutation eligibility is the server’s separate authorization for one write. Ineligible entries remain visible for inspection.',
  searchPlaceholder: 'Search ID, package, category, or management plane', searchEmpty: 'No matching capabilities.', searchEmptyAnomalies: 'No anomalies found.', searchEmptyAnomaliesFiltered: 'No anomalies found under the current filters.', resultCount: 'Showing {count} / {total} capabilities',
  compatibilityHeading: 'Compatibility / Doctor', compatibilityStatusDrifted: 'Structural drift found', compatibilityStatusNoDrift: 'No structural drift found', compatibilityExplainDrifted: 'A reviewable structural difference was observed. Inspection remains available, but these findings need evaluation in a compatibility report.', compatibilityExplainIdentityMismatch: 'The Host-exposed runtime release identity does not match the reviewed baseline; this is not a general health judgment about the Host.', compatibilityExplainEvidenceIncomplete: 'The reviewed baseline contains evidence that could not be independently confirmed, so the result remains unverified.', compatibilityExplainIdentityUnavailable: 'The Host has not exposed a bindable runtime release identity. This does not mean the system is broken or a capability is unavailable.', compatibilityExplainUnverified: 'Available evidence is insufficient for a verified conclusion; review the findings below.', compatibilityExplainVerified: 'Structure and runtime identity are aligned; no structural drift found.', compatibilityExplainNoDrift: 'No structural drift found; only the upstream-unavailable runtime release identity is missing and remains in machine evidence.', runtimeIdentityLabel: 'Runtime identity', noFindings: 'No reportable findings.', copyDiagnostics: 'Copy diagnostics', diagnosticsCopied: 'Redacted diagnostics copied.', diagnosticsCopyFailed: 'Could not copy diagnostics.',
  filterAll: 'All', filterCategory: 'Category', filterManagementPlane: 'Management plane', filterCompositionScope: 'Composition scope', filterPolicy: 'Policy', filterVerification: 'Inspection status', filterRuntime: 'Runtime state', filterAnomalies: 'Anomalies only',
  capabilityName: 'Name: {name}', presetManaged: 'Managed by Agent Preset', effectiveDisabled: 'Effective: disabled', effectiveEnabled: 'Effective: enabled', detailsShow: 'Show machine evidence', detailsHide: 'Hide machine evidence', lockReason: 'Lock reason', compositionScope: 'Composition scope',
  mutationControls: 'Mutation controls', forceEnable: 'Force enable', forceDisable: 'Force disable', restoreInheritance: 'Restore inheritance', controlsUnavailable: 'No executable controls for this entry', remoteReadOnly: 'Remote Inspector is read-only; configuration mutation requires loopback same-origin access.', remoteReadOnlyEligible: 'This item could be modified locally, but the current remote read-only mode prevents mutation.', mutationFailed: 'Mutation failed: {message}', mutationSubmitted: 'Submitted. The authoritative server state was re-read; refresh to update the loaded client.', restoreSubmitted: 'Profile inheritance restored. The authoritative server state was re-read; effective state may differ temporarily while DSH profile/HMR recomposes.',
  copyCopied: 'Copied', copyFailed: 'Copy failed',
  expectedPackage: 'Expected package', reviewed: 'Reviewed', reviewedReference: 'Reviewed reference / provenance', declaredInject: 'Declared inject evidence', dependencyEvidence: 'Dependency evidence', leafReview: 'Leaf review conclusion', compatibilityFindings: 'Compatibility findings', eligibilityReasons: 'Eligibility reasons', limitations: 'Limitations', provides: 'Provides', consumers: 'Consumers', profilePersistence: 'Profile persistence preflight',
  yes: 'Yes', no: 'No', none: 'None', unknown: 'Unknown', noEvidence: 'No available evidence', injectNotDeclared: 'Reviewed patch declares no inject array', injectDeclaredEmpty: 'Declared empty inject set', dependencyObserved: 'Observed',
  verificationVerified: 'Verified', verificationDrifted: 'Drifted', verificationUnverified: 'Unverified', verificationNoDrift: 'No structural drift observed', verificationEvidenceIncomplete: 'Evidence incomplete', verificationIdentityMismatch: 'Runtime identity mismatch', verificationUnreviewed: 'Unreviewed', verificationNotApplicable: 'Agent Preset; not a baseline verification target', runtimeIdentityMatched: 'Matched', runtimeIdentityMismatched: 'Mismatched', runtimeIdentityUnavailable: 'Unavailable',
  profileInherited: 'Inherited', profileExplicitlyEnabled: 'Explicitly enabled', profileExplicitlyDisabled: 'Explicitly disabled', profileUnavailable: 'Unavailable', profileNotApplicable: 'Not applicable (Agent Preset composition)', profileWritable: 'Writable', profileUnwritable: 'Unwritable',
  lifecycleInactive: 'Inactive', lifecyclePending: 'Pending', lifecycleLoading: 'Loading', lifecycleActive: 'Active', lifecycleFailed: 'Failed', lifecycleUnloading: 'Unloading', lifecycleUnknown: 'Unknown',
  findingMissingExpectedEntry: 'Missing expected entry', findingNewOfficialEntry: 'New official entry', findingPackageIdentityChanged: 'Package identity drift', findingDeclaredInjectChanged: 'Inject drift', findingBaselinePackageUnknown: 'Baseline package identity unknown', findingDuplicateRuntimeId: 'Duplicate Loader ID', findingRuntimeReleaseIdentityUnavailable: 'Runtime identity unavailable', findingRuntimeReleaseIdentityMismatch: 'Runtime identity mismatch', findingRuntimeAugmentationShapeChanged: 'Runtime augmentation shape changed', findingRuntimeAugmentationIdConflictsBaseline: 'Runtime augmentation id conflicts with baseline',
  eligibilityNotManageable: 'Not in manageable allowlist', eligibilityMissingRuntimeEntry: 'Missing runtime entry', eligibilityReviewedBaselineMissing: 'Missing reviewed baseline', eligibilityReviewedSafeLeafEvidenceMissing: 'Missing safe-leaf evidence', eligibilityTargetStructuralDrift: 'Target structural drift', eligibilityGlobalStructuralDrift: 'Global structural drift', eligibilityRuntimeIdentityMismatch: 'Runtime identity mismatch', eligibilityProfileNotPersistable: 'Profile cannot be safely written', eligibilityAgentPresetScope: 'Agent Preset composition rows are not Host mutation targets',
  limitationRuntimeIdentityUnavailable: 'Runtime release identity unavailable', limitationConsumerGraphNotExposed: 'Consumer graph not exposed',
  leafReviewReviewedSafeUiLeaf: 'Reviewed safe UI leaf', leafReviewLockedDependency: 'Locked dependency', leafReviewNotReviewed: 'Not reviewed',
  categoryPresentation: 'Presentation', categoryAgent: 'Agent', categoryTransport: 'Transport', categoryInfrastructure: 'Infrastructure', categoryUnknown: 'Unknown category', planeBrowser: 'Browser', planeHost: 'Host', planeAgentPreset: 'Agent Preset', planeUnknown: 'Unknown plane', policyManageable: 'Manageable', policyLocked: 'Locked', lockSelf: 'Plugin itself', lockCore: 'Core infrastructure', lockUnlisted: 'Not on allowlist', lockExternal: 'External plugin', lockAgentPreset: 'Agent Preset composition row',
}
